import { R2021_SEM1_COMMON, R2021_SEM2_COMMON_MECH } from './common'

export const EEE = {
  name: 'Electrical & Electronics Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: [
      { code: 'HS3251', name: 'Professional English II', credits: 4, type: 'theory' },
      { code: 'MA3251', name: 'Statistics & Numerical Methods', credits: 4, type: 'theory' },
      { code: 'PH3252', name: 'Physics for Mechanical Sciences', credits: 3, type: 'theory' },
      { code: 'EE3251', name: 'Circuit Theory', credits: 4, type: 'theory' },
      { code: 'EE3252', name: 'Electron Devices & Circuits', credits: 3, type: 'theory' },
      { code: 'GE3251', name: 'Engineering Graphics', credits: 4, type: 'theory' },
      { code: 'EE3271', name: 'Electric Circuits Lab', credits: 2, type: 'lab' },
      { code: 'GE3271', name: 'Engineering Practices Lab', credits: 2, type: 'lab' },
    ],
    3: [
      { code: 'MA3351', name: 'Transforms & Partial Differential Equations', credits: 4, type: 'theory' },
      { code: 'EE3351', name: 'Digital Logic Circuits', credits: 4, type: 'theory' },
      { code: 'EE3391', name: 'Electromagnetic Theory', credits: 3, type: 'theory' },
      { code: 'EE3301', name: 'Electrical Machines I', credits: 3, type: 'theory' },
      { code: 'EE3352', name: 'Signals & Systems', credits: 3, type: 'theory' },
      { code: 'EE3302', name: 'Measurements & Instrumentation', credits: 3, type: 'theory' },
      { code: 'EE3311', name: 'Electrical Machines Lab I', credits: 2, type: 'lab' },
      { code: 'EE3381', name: 'Measurements Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MA3491', name: 'Numerical Methods', credits: 4, type: 'theory' },
      { code: 'EE3401', name: 'Electrical Machines II', credits: 3, type: 'theory' },
      { code: 'EE3402', name: 'Transmission & Distribution', credits: 3, type: 'theory' },
      { code: 'EE3451', name: 'Linear Integrated Circuits', credits: 3, type: 'theory' },
      { code: 'EE3491', name: 'Control Systems', credits: 4, type: 'theory' },
      { code: 'EE3404', name: 'Power System Analysis', credits: 3, type: 'theory' },
      { code: 'EE3411', name: 'Electrical Machines Lab II', credits: 2, type: 'lab' },
      { code: 'EE3461', name: 'Linear & Digital ICs Lab', credits: 2, type: 'lab' },
      { code: 'MX3411', name: 'Naan Mudhalvan: Technical Skills', credits: 2, type: 'lab' },
    ],
    5: [
      { code: 'EE3501', name: 'Power Electronics', credits: 4, type: 'theory' },
      { code: 'EE3551', name: 'Microprocessors & Microcontrollers', credits: 3, type: 'theory' },
      { code: 'EE3591', name: 'Digital Signal Processing', credits: 4, type: 'theory' },
      { code: 'EE3502', name: 'Power System Operation & Control', credits: 3, type: 'theory' },
      { code: 'CEE3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'EE3511', name: 'Control & Instrumentation Lab', credits: 2, type: 'lab' },
      { code: 'EE3512', name: 'Microprocessors Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'EE3601', name: 'Solid State Drives', credits: 3, type: 'theory' },
      { code: 'EE3602', name: 'Protection & Switchgear', credits: 3, type: 'theory' },
      { code: 'EE3691', name: 'Embedded Systems', credits: 4, type: 'theory' },
      { code: 'CEE3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CEE3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'EE3611', name: 'Power Electronics & Drives Lab', credits: 2, type: 'lab' },
      { code: 'EE3681', name: 'Power Systems Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'EE3701', name: 'High Voltage Engineering', credits: 3, type: 'theory' },
      { code: 'CEE3AA', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'CEE3BB', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'EE3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'EE3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'CEE3CC', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const MECH = {
  name: 'Mechanical Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_MECH,
    3: [
      { code: 'MA3351', name: 'Transforms & Partial Differential Equations', credits: 4, type: 'theory' },
      { code: 'ME3391', name: 'Engineering Thermodynamics', credits: 4, type: 'theory' },
      { code: 'CE3391', name: 'Strength of Materials', credits: 4, type: 'theory' },
      { code: 'ME3351', name: 'Manufacturing Technology I', credits: 3, type: 'theory' },
      { code: 'ME3301', name: 'Fluid Mechanics & Machinery', credits: 3, type: 'theory' },
      { code: 'ME3361', name: 'Manufacturing Technology Lab I', credits: 2, type: 'lab' },
      { code: 'ME3381', name: 'Computer Aided Machine Drawing', credits: 2, type: 'lab' },
      { code: 'ME3311', name: 'Strength of Materials Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MA3491', name: 'Numerical Methods', credits: 4, type: 'theory' },
      { code: 'ME3451', name: 'Manufacturing Technology II', credits: 3, type: 'theory' },
      { code: 'ME3492', name: 'Kinematics of Machinery', credits: 3, type: 'theory' },
      { code: 'ME3493', name: 'Thermal Engineering I', credits: 3, type: 'theory' },
      { code: 'ME3491', name: 'Engineering Metallurgy', credits: 3, type: 'theory' },
      { code: 'ME3494', name: 'Fluid Mechanics & Machinery', credits: 4, type: 'theory' },
      { code: 'ME3461', name: 'Manufacturing Technology Lab II', credits: 2, type: 'lab' },
      { code: 'ME3462', name: 'Thermal Engineering Lab I', credits: 2, type: 'lab' },
      { code: 'MX3411', name: 'Naan Mudhalvan: Technical Skills', credits: 2, type: 'lab' },
    ],
    5: [
      { code: 'ME3593', name: 'Design of Machine Elements', credits: 3, type: 'theory' },
      { code: 'ME3594', name: 'Dynamics of Machines', credits: 3, type: 'theory' },
      { code: 'ME3595', name: 'Thermal Engineering II', credits: 3, type: 'theory' },
      { code: 'ME3501', name: 'Metrology & Measurements', credits: 3, type: 'theory' },
      { code: 'CME3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'ME3511', name: 'Dynamics Lab', credits: 2, type: 'lab' },
      { code: 'ME3512', name: 'Thermal Engineering Lab II', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'ME3651', name: 'Design of Transmission Systems', credits: 3, type: 'theory' },
      { code: 'ME3652', name: 'Finite Element Analysis', credits: 3, type: 'theory' },
      { code: 'ME3691', name: 'CAD / CAM', credits: 3, type: 'theory' },
      { code: 'CME3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CME3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'ME3681', name: 'CAD / CAM Lab', credits: 2, type: 'lab' },
      { code: 'ME3682', name: 'Design & Fabrication Project', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'ME3792', name: 'Power Plant Engineering', credits: 3, type: 'theory' },
      { code: 'CME3AA', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'CME3BB', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'ME3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'ME3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'CME3CC', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const CIVIL = {
  name: 'Civil Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_MECH,
    3: [
      { code: 'MA3351', name: 'Transforms & Partial Differential Equations', credits: 4, type: 'theory' },
      { code: 'CE3391', name: 'Construction Materials', credits: 3, type: 'theory' },
      { code: 'CE3392', name: 'Engineering Geology', credits: 3, type: 'theory' },
      { code: 'CE3301', name: 'Strength of Materials I', credits: 4, type: 'theory' },
      { code: 'CE3351', name: 'Surveying', credits: 3, type: 'theory' },
      { code: 'CE3394', name: 'Fluid Mechanics', credits: 3, type: 'theory' },
      { code: 'CE3311', name: 'Surveying Lab', credits: 2, type: 'lab' },
      { code: 'CE3381', name: 'Strength of Materials Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MA3491', name: 'Numerical Methods', credits: 4, type: 'theory' },
      { code: 'CE3401', name: 'Construction Techniques', credits: 3, type: 'theory' },
      { code: 'CE3402', name: 'Strength of Materials II', credits: 3, type: 'theory' },
      { code: 'CE3491', name: 'Soil Mechanics', credits: 3, type: 'theory' },
      { code: 'CE3404', name: 'Concrete Technology', credits: 3, type: 'theory' },
      { code: 'CE3403', name: 'Applied Hydraulic Engineering', credits: 4, type: 'theory' },
      { code: 'CE3411', name: 'Hydraulic Engineering Lab', credits: 2, type: 'lab' },
      { code: 'CE3461', name: 'Soil Mechanics Lab', credits: 2, type: 'lab' },
    ],
    5: [
      { code: 'CE3501', name: 'Design of RC Elements', credits: 4, type: 'theory' },
      { code: 'CE3502', name: 'Structural Analysis I', credits: 3, type: 'theory' },
      { code: 'CE3591', name: 'Foundation Engineering', credits: 3, type: 'theory' },
      { code: 'CE3504', name: 'Water Supply Engineering', credits: 3, type: 'theory' },
      { code: 'CCE3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'CE3511', name: 'Concrete & Highway Lab', credits: 2, type: 'lab' },
      { code: 'CE3513', name: 'Survey Camp', credits: 1, type: 'lab' },
    ],
    6: [
      { code: 'CE3601', name: 'Design of Steel Structures', credits: 3, type: 'theory' },
      { code: 'CE3602', name: 'Structural Analysis II', credits: 3, type: 'theory' },
      { code: 'CE3603', name: 'Highway Engineering', credits: 3, type: 'theory' },
      { code: 'CE3604', name: 'Wastewater Engineering', credits: 3, type: 'theory' },
      { code: 'CCE3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'CE3611', name: 'Environmental Engineering Lab', credits: 2, type: 'lab' },
      { code: 'CE3612', name: 'Quantity Surveying', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CE3701', name: 'Estimation & Quantity Surveying', credits: 3, type: 'theory' },
      { code: 'CCE3AA', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CCE3BB', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'CE3711', name: 'Design & Drawing Lab', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'CE3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'CCE3CC', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const BME = {
  name: 'Biomedical Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: [
      { code: 'HS3251', name: 'Professional English II', credits: 4, type: 'theory' },
      { code: 'MA3251', name: 'Statistics & Numerical Methods', credits: 4, type: 'theory' },
      { code: 'PH3254', name: 'Physics for Electronics Engineering', credits: 3, type: 'theory' },
      { code: 'BE3251', name: 'Basic Electrical & Electronics Engineering', credits: 3, type: 'theory' },
      { code: 'GE3251', name: 'Engineering Graphics', credits: 4, type: 'theory' },
      { code: 'BM3251', name: 'Human Anatomy & Physiology', credits: 3, type: 'theory' },
      { code: 'GE3271', name: 'Engineering Practices Lab', credits: 2, type: 'lab' },
      { code: 'BM3271', name: 'Anatomy & Physiology Lab', credits: 2, type: 'lab' },
    ],
    3: [
      { code: 'MA3351', name: 'Transforms & PDE', credits: 4, type: 'theory' },
      { code: 'BM3301', name: 'Biomedical Instrumentation', credits: 3, type: 'theory' },
      { code: 'BM3302', name: 'Biomechanics', credits: 3, type: 'theory' },
      { code: 'EC3391', name: 'Digital Electronics', credits: 4, type: 'theory' },
      { code: 'BM3351', name: 'Signals & Systems', credits: 3, type: 'theory' },
      { code: 'BM3311', name: 'Biomedical Instrumentation Lab', credits: 2, type: 'lab' },
      { code: 'EC3311', name: 'Digital Electronics Lab', credits: 2, type: 'lab' },
      { code: 'CS3271', name: 'Programming in C Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'BM3401', name: 'Medical Imaging', credits: 4, type: 'theory' },
      { code: 'BM3402', name: 'Biosensors & Transducers', credits: 3, type: 'theory' },
      { code: 'BM3403', name: 'Biomedical Signal Processing', credits: 3, type: 'theory' },
      { code: 'BM3451', name: 'Pathology & Microbiology', credits: 3, type: 'theory' },
      { code: 'EC3401', name: 'Linear Integrated Circuits', credits: 3, type: 'theory' },
      { code: 'BM3411', name: 'Medical Imaging Lab', credits: 2, type: 'lab' },
      { code: 'BM3481', name: 'Signal Processing Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'BM3501', name: 'Biomaterials', credits: 3, type: 'theory' },
      { code: 'BM3502', name: 'Hospital Management', credits: 3, type: 'theory' },
      { code: 'BM3503', name: 'Rehabilitation Engineering', credits: 3, type: 'theory' },
      { code: 'BM3551', name: 'Therapeutic Equipment', credits: 3, type: 'theory' },
      { code: 'CBM3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'BM3511', name: 'Biomaterials Lab', credits: 2, type: 'lab' },
      { code: 'BM3581', name: 'Virtual Instrumentation Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'BM3601', name: 'Clinical Engineering', credits: 3, type: 'theory' },
      { code: 'BM3691', name: 'Artificial Organs & Prosthetics', credits: 3, type: 'theory' },
      { code: 'CBM3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CBM3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CBM3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'BM3611', name: 'Clinical Engineering Lab', credits: 2, type: 'lab' },
      { code: 'BM3681', name: 'Mini Project', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CBM3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CBM3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'BM3711', name: 'Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'BM3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const MECT = {
  name: 'Mechatronics Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_MECH,
    3: [
      { code: 'MA3351', name: 'Transforms & Partial Differential Equations', credits: 4, type: 'theory' },
      { code: 'MT3301', name: 'Sensors & Actuators', credits: 3, type: 'theory' },
      { code: 'MT3302', name: 'Electrical Machines & Drives', credits: 3, type: 'theory' },
      { code: 'ME3391', name: 'Engineering Thermodynamics', credits: 4, type: 'theory' },
      { code: 'CE3391', name: 'Strength of Materials', credits: 4, type: 'theory' },
      { code: 'MT3311', name: 'Sensors & Actuators Lab', credits: 2, type: 'lab' },
      { code: 'MT3381', name: 'Electrical Drives Lab', credits: 2, type: 'lab' },
      { code: 'ME3381', name: 'CAD Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MT3401', name: 'Control Systems', credits: 4, type: 'theory' },
      { code: 'MT3402', name: 'Robotics', credits: 3, type: 'theory' },
      { code: 'MT3403', name: 'Embedded Systems', credits: 3, type: 'theory' },
      { code: 'MT3404', name: 'PLC & SCADA', credits: 3, type: 'theory' },
      { code: 'MT3451', name: 'Hydraulics & Pneumatics', credits: 3, type: 'theory' },
      { code: 'MT3411', name: 'Robotics Lab', credits: 2, type: 'lab' },
      { code: 'MT3461', name: 'Embedded Systems Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'MT3501', name: 'Mechatronics System Design', credits: 3, type: 'theory' },
      { code: 'MT3502', name: 'CNC Machines', credits: 3, type: 'theory' },
      { code: 'MT3503', name: 'MEMS', credits: 3, type: 'theory' },
      { code: 'MT3551', name: 'Industrial IoT', credits: 3, type: 'theory' },
      { code: 'CMT3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'MT3511', name: 'PLC & SCADA Lab', credits: 2, type: 'lab' },
      { code: 'MT3581', name: 'CNC Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'MT3601', name: 'Machine Vision', credits: 3, type: 'theory' },
      { code: 'CMT3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CMT3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CMT3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'MT3611', name: 'Machine Vision Lab', credits: 2, type: 'lab' },
      { code: 'MT3681', name: 'Mini Project', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CMT3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CMT3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'MT3711', name: 'Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'MT3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}
