import { R2021_SEM1_COMMON, R2021_SEM2_COMMON_CSE } from './common'

export const CSE = {
  name: 'Computer Science & Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'CS3352', name: 'Foundations of Data Science', credits: 3, type: 'theory' },
      { code: 'CS3391', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'CS3381', name: 'Object Oriented Programming Lab', credits: 2, type: 'lab' },
      { code: 'CS3311', name: 'Data Structures Lab', credits: 2, type: 'lab' },
      { code: 'CS3361', name: 'Data Science Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'CS3452', name: 'Theory of Computation', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'Artificial Intelligence & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'CS3451', name: 'Introduction to Operating Systems', credits: 3, type: 'theory' },
      { code: 'CS3461', name: 'Operating Systems Lab', credits: 2, type: 'lab' },
      { code: 'CS3481', name: 'Database Management Systems Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'CS3501', name: 'Compiler Design', credits: 3, type: 'theory' },
      { code: 'CB3491', name: 'Cryptography & Cyber Security', credits: 4, type: 'theory' },
      { code: 'CS3551', name: 'Distributed Computing', credits: 3, type: 'theory' },
      { code: 'CCS3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'CS3581', name: 'Networks Lab', credits: 2, type: 'lab' },
      { code: 'CS3511', name: 'Compiler Design Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'CCS356', name: 'Object Oriented Software Engineering', credits: 3, type: 'theory' },
      { code: 'CS3691', name: 'Embedded Systems & IoT', credits: 3, type: 'theory' },
      { code: 'CCS3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CCS3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CCS3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'CS3611', name: 'IoT Lab', credits: 2, type: 'lab' },
      { code: 'CCS3PP', name: 'Professional Elective Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CCS3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CCS3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'CS3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
      { code: 'GE3771', name: 'Aptitude & Logical Reasoning', credits: 1, type: 'theory' },
    ],
    8: [
      { code: 'CS3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const ECE = {
  name: 'Electronics & Communication Engineering',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: [
      { code: 'HS3251', name: 'Professional English II', credits: 4, type: 'theory' },
      { code: 'MA3251', name: 'Statistics & Numerical Methods', credits: 4, type: 'theory' },
      { code: 'PH3254', name: 'Physics for Electronics Engineering', credits: 3, type: 'theory' },
      { code: 'BE3251', name: 'Basic Electrical & Electronics Engineering', credits: 3, type: 'theory' },
      { code: 'GE3251', name: 'Engineering Graphics', credits: 4, type: 'theory' },
      { code: 'CS3251', name: 'Programming in C', credits: 3, type: 'theory' },
      { code: 'GE3271', name: 'Engineering Practices Lab', credits: 2, type: 'lab' },
      { code: 'CS3271', name: 'Programming in C Lab', credits: 2, type: 'lab' },
    ],
    3: [
      { code: 'MA3351', name: 'Transforms & Partial Differential Equations', credits: 4, type: 'theory' },
      { code: 'EC3351', name: 'Signals & Systems', credits: 3, type: 'theory' },
      { code: 'EC3301', name: 'Electronic Circuits', credits: 4, type: 'theory' },
      { code: 'EC3391', name: 'Digital Electronics', credits: 4, type: 'theory' },
      { code: 'EC3352', name: 'Electromagnetic Fields', credits: 3, type: 'theory' },
      { code: 'EC3381', name: 'Analog & Digital Circuits Lab', credits: 2, type: 'lab' },
      { code: 'EC3311', name: 'Digital Electronics Lab', credits: 2, type: 'lab' },
      { code: 'EC3361', name: 'Circuit Simulation Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MA3451', name: 'Probability & Random Processes', credits: 4, type: 'theory' },
      { code: 'EC3491', name: 'Communication Theory', credits: 4, type: 'theory' },
      { code: 'EC3401', name: 'Linear Integrated Circuits', credits: 3, type: 'theory' },
      { code: 'EC3451', name: 'Control Systems', credits: 3, type: 'theory' },
      { code: 'EC3492', name: 'Digital Signal Processing', credits: 3, type: 'theory' },
      { code: 'EC3461', name: 'Linear Integrated Circuits Lab', credits: 2, type: 'lab' },
      { code: 'EC3481', name: 'Communication Systems Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
      { code: 'MX3411', name: 'Naan Mudhalvan: Technical Skill Training', credits: 2, type: 'lab' },
    ],
    5: [
      { code: 'EC3551', name: 'Transmission Lines & RF Systems', credits: 3, type: 'theory' },
      { code: 'EC3591', name: 'Wireless Communication', credits: 3, type: 'theory' },
      { code: 'EC3501', name: 'Microprocessors & Microcontrollers', credits: 4, type: 'theory' },
      { code: 'EC3552', name: 'VLSI Design', credits: 3, type: 'theory' },
      { code: 'CEC3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'EC3511', name: 'Microprocessors Lab', credits: 2, type: 'lab' },
      { code: 'EC3581', name: 'DSP & Comm. Systems Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'EC3651', name: 'Embedded Systems', credits: 3, type: 'theory' },
      { code: 'EC3691', name: 'Antenna & Wave Propagation', credits: 3, type: 'theory' },
      { code: 'CEC3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CEC3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CEC3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'EC3611', name: 'VLSI Design Lab', credits: 2, type: 'lab' },
      { code: 'EC3681', name: 'Embedded Systems Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CEC3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CEC3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'EC3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'EC3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const IT = {
  name: 'Information Technology',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'IT3301', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'IT3302', name: 'Software Engineering', credits: 3, type: 'theory' },
      { code: 'IT3311', name: 'OOP Lab', credits: 2, type: 'lab' },
      { code: 'IT3352', name: 'Data Structures & Algorithms Lab', credits: 2, type: 'lab' },
      { code: 'IT3361', name: 'Software Engineering Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'CS3452', name: 'Theory of Computation', credits: 3, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'Artificial Intelligence & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'CS3451', name: 'Introduction to Operating Systems', credits: 3, type: 'theory' },
      { code: 'CS3461', name: 'Operating Systems Lab', credits: 2, type: 'lab' },
      { code: 'CS3481', name: 'Database Management Systems Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'IT3501', name: 'Web Technology', credits: 3, type: 'theory' },
      { code: 'CB3491', name: 'Cryptography & Cyber Security', credits: 4, type: 'theory' },
      { code: 'IT3502', name: 'Digital Signal Processing', credits: 4, type: 'theory' },
      { code: 'CIT3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'CS3581', name: 'Networks Lab', credits: 2, type: 'lab' },
      { code: 'IT3511', name: 'Web Technology Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'IT3601', name: 'Mobile Applications Development', credits: 3, type: 'theory' },
      { code: 'IT3602', name: 'Software Testing', credits: 3, type: 'theory' },
      { code: 'CIT3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CIT3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CIT3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'IT3611', name: 'Mobile Application Development Lab', credits: 2, type: 'lab' },
      { code: 'IT3681', name: 'Software Testing Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'IT3701', name: 'Information Management', credits: 3, type: 'theory' },
      { code: 'CIT3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CIT3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'IT3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'IT3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const AIDS = {
  name: 'Artificial Intelligence & Data Science',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'AD3301', name: 'Data Exploration & Visualization', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'CS3391', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3311', name: 'Data Structures Lab', credits: 2, type: 'lab' },
      { code: 'CS3381', name: 'Object Oriented Programming Lab', credits: 2, type: 'lab' },
      { code: 'AD3311', name: 'Data Exploration Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MA3391', name: 'Probability & Statistics', credits: 4, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'Artificial Intelligence & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'AD3401', name: 'Neural Networks & Deep Learning', credits: 3, type: 'theory' },
      { code: 'CS3481', name: 'DBMS Lab', credits: 2, type: 'lab' },
      { code: 'AD3411', name: 'AI & ML Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'AD3501', name: 'Natural Language Processing', credits: 3, type: 'theory' },
      { code: 'AD3502', name: 'Big Data & Cloud Computing', credits: 3, type: 'theory' },
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'AD3551', name: 'Computer Vision', credits: 3, type: 'theory' },
      { code: 'CAD3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'AD3511', name: 'NLP Lab', credits: 2, type: 'lab' },
      { code: 'AD3581', name: 'Big Data Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'AD3601', name: 'Reinforcement Learning', credits: 3, type: 'theory' },
      { code: 'AD3691', name: 'IoT & Edge AI', credits: 3, type: 'theory' },
      { code: 'CAD3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CAD3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CAD3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'AD3611', name: 'AI Applications Lab', credits: 2, type: 'lab' },
      { code: 'AD3681', name: 'IoT Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CAD3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CAD3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'AD3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'AD3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const CSBS = {
  name: 'Computer Science & Business Systems',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'CB3301', name: 'Business Analytics', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'CS3391', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3311', name: 'Data Structures Lab', credits: 2, type: 'lab' },
      { code: 'CS3381', name: 'Object Oriented Programming Lab', credits: 2, type: 'lab' },
      { code: 'CB3311', name: 'Business Analytics Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'CS3452', name: 'Theory of Computation', credits: 3, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'AI & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'CB3401', name: 'Financial Management', credits: 3, type: 'theory' },
      { code: 'CS3481', name: 'DBMS Lab', credits: 2, type: 'lab' },
      { code: 'CB3411', name: 'AI & Business Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'CB3491', name: 'Cryptography & Cyber Security', credits: 4, type: 'theory' },
      { code: 'CB3501', name: 'Supply Chain Management', credits: 3, type: 'theory' },
      { code: 'CB3502', name: 'Data Mining & Warehousing', credits: 3, type: 'theory' },
      { code: 'CCB3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'CS3581', name: 'Networks Lab', credits: 2, type: 'lab' },
      { code: 'CB3511', name: 'Data Mining Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'CB3601', name: 'Digital Marketing', credits: 3, type: 'theory' },
      { code: 'CB3602', name: 'ERP Systems', credits: 3, type: 'theory' },
      { code: 'CCB3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CCB3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CCB3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'CB3611', name: 'Business Systems Lab', credits: 2, type: 'lab' },
      { code: 'CB3681', name: 'Project Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CCB3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CCB3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'CB3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'CB3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const CSD = {
  name: 'Computer Science & Design',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'CD3301', name: 'Design Thinking & Innovation', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'CS3391', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3311', name: 'Data Structures Lab', credits: 2, type: 'lab' },
      { code: 'CS3381', name: 'OOP Lab', credits: 2, type: 'lab' },
      { code: 'CD3311', name: 'UI/UX Design Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'CS3452', name: 'Theory of Computation', credits: 3, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'AI & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'CD3401', name: 'Human Computer Interaction', credits: 3, type: 'theory' },
      { code: 'CS3481', name: 'DBMS Lab', credits: 2, type: 'lab' },
      { code: 'CD3411', name: 'HCI Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'CD3501', name: 'Interactive Media Design', credits: 3, type: 'theory' },
      { code: 'CD3502', name: 'Computer Graphics & Visualization', credits: 3, type: 'theory' },
      { code: 'CB3491', name: 'Cryptography & Cyber Security', credits: 4, type: 'theory' },
      { code: 'CCD3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'CD3511', name: 'Graphics & Design Lab', credits: 2, type: 'lab' },
      { code: 'CS3581', name: 'Networks Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'CD3601', name: 'Game Design & Development', credits: 3, type: 'theory' },
      { code: 'CD3602', name: 'AR / VR Technologies', credits: 3, type: 'theory' },
      { code: 'CCD3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CCD3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CCD3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'CD3611', name: 'Game Development Lab', credits: 2, type: 'lab' },
      { code: 'CD3681', name: 'AR/VR Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CCD3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CCD3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'CD3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'CD3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const CSE_CS = {
  name: 'CSE (Cyber Security)',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'CY3301', name: 'Computer System Security', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'CS3391', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3311', name: 'Data Structures Lab', credits: 2, type: 'lab' },
      { code: 'CS3381', name: 'OOP Lab', credits: 2, type: 'lab' },
      { code: 'CY3311', name: 'Security Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'CS3452', name: 'Theory of Computation', credits: 3, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'AI & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'CY3401', name: 'Network Security', credits: 3, type: 'theory' },
      { code: 'CS3481', name: 'DBMS Lab', credits: 2, type: 'lab' },
      { code: 'CY3411', name: 'Network Security Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'CY3501', name: 'Ethical Hacking & Penetration Testing', credits: 3, type: 'theory' },
      { code: 'CY3502', name: 'Digital Forensics', credits: 3, type: 'theory' },
      { code: 'CB3491', name: 'Cryptography & Cyber Security', credits: 4, type: 'theory' },
      { code: 'CCY3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'CY3511', name: 'Ethical Hacking Lab', credits: 2, type: 'lab' },
      { code: 'CS3581', name: 'Networks Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'CY3601', name: 'Malware Analysis', credits: 3, type: 'theory' },
      { code: 'CY3602', name: 'Cloud Security', credits: 3, type: 'theory' },
      { code: 'CCY3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CCY3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CCY3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'CY3611', name: 'Forensics Lab', credits: 2, type: 'lab' },
      { code: 'CY3681', name: 'Cloud Security Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CCY3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CCY3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'CY3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'CY3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}

export const AIML = {
  name: 'CSE (AI & Machine Learning)',
  semesters: {
    1: R2021_SEM1_COMMON,
    2: R2021_SEM2_COMMON_CSE,
    3: [
      { code: 'MA3354', name: 'Discrete Mathematics', credits: 4, type: 'theory' },
      { code: 'CS3351', name: 'Digital Principles & Computer Organization', credits: 4, type: 'theory' },
      { code: 'AL3301', name: 'Machine Learning Foundations', credits: 3, type: 'theory' },
      { code: 'CS3301', name: 'Data Structures', credits: 3, type: 'theory' },
      { code: 'CS3391', name: 'Object Oriented Programming', credits: 3, type: 'theory' },
      { code: 'CS3311', name: 'Data Structures Lab', credits: 2, type: 'lab' },
      { code: 'CS3381', name: 'OOP Lab', credits: 2, type: 'lab' },
      { code: 'AL3311', name: 'ML Foundations Lab', credits: 2, type: 'lab' },
    ],
    4: [
      { code: 'MA3391', name: 'Probability & Statistics', credits: 4, type: 'theory' },
      { code: 'CS3492', name: 'Database Management Systems', credits: 3, type: 'theory' },
      { code: 'CS3491', name: 'Artificial Intelligence & Machine Learning', credits: 4, type: 'theory' },
      { code: 'CS3401', name: 'Algorithms', credits: 4, type: 'theory' },
      { code: 'AL3401', name: 'Deep Learning', credits: 3, type: 'theory' },
      { code: 'CS3481', name: 'DBMS Lab', credits: 2, type: 'lab' },
      { code: 'AL3411', name: 'Deep Learning Lab', credits: 2, type: 'lab' },
      { code: 'GE3451', name: 'Environmental Sciences & Sustainability', credits: 2, type: 'theory' },
    ],
    5: [
      { code: 'CS3591', name: 'Computer Networks', credits: 3, type: 'theory' },
      { code: 'AL3501', name: 'Natural Language Processing', credits: 3, type: 'theory' },
      { code: 'AL3502', name: 'Computer Vision', credits: 3, type: 'theory' },
      { code: 'CB3491', name: 'Cryptography & Cyber Security', credits: 4, type: 'theory' },
      { code: 'CAL3XX', name: 'Professional Elective I', credits: 3, type: 'elective' },
      { code: 'OXXYYY', name: 'Open Elective I', credits: 3, type: 'elective' },
      { code: 'AL3511', name: 'NLP Lab', credits: 2, type: 'lab' },
      { code: 'AL3581', name: 'Computer Vision Lab', credits: 2, type: 'lab' },
    ],
    6: [
      { code: 'AL3601', name: 'Reinforcement Learning', credits: 3, type: 'theory' },
      { code: 'AL3602', name: 'Generative AI & LLMs', credits: 3, type: 'theory' },
      { code: 'CAL3YY', name: 'Professional Elective II', credits: 3, type: 'elective' },
      { code: 'CAL3ZZ', name: 'Professional Elective III', credits: 3, type: 'elective' },
      { code: 'CAL3WW', name: 'Professional Elective IV', credits: 3, type: 'elective' },
      { code: 'OXXZZZ', name: 'Open Elective II', credits: 3, type: 'elective' },
      { code: 'AL3611', name: 'AI Applications Lab', credits: 2, type: 'lab' },
      { code: 'AL3681', name: 'Gen AI Lab', credits: 2, type: 'lab' },
    ],
    7: [
      { code: 'CAL3AA', name: 'Professional Elective V', credits: 3, type: 'elective' },
      { code: 'CAL3BB', name: 'Professional Elective VI', credits: 3, type: 'elective' },
      { code: 'OXXWWW', name: 'Open Elective III', credits: 3, type: 'elective' },
      { code: 'GE3791', name: 'Human Values & Ethics', credits: 2, type: 'theory' },
      { code: 'AL3711', name: 'Mini Project / Internship', credits: 3, type: 'lab' },
    ],
    8: [
      { code: 'AL3811', name: 'Project Work / Dissertation', credits: 10, type: 'lab' },
      { code: 'OXXVVV', name: 'Open Elective IV', credits: 3, type: 'elective' },
    ],
  },
}
